name: sim_data_plus
description: A Flutter plugin to retrieve Sim cards data - dual sim support - only Android for now.
version: 0.1.4
homepage: https://github.com/shrijeetx/sim_data_plus.git
documentation: https://github.com/shrijeetx/sim_data_plus.git
repository: https://github.com/shrijeetx/sim_data_plus.git
issue_tracker: https://github.com/shrijeetx/sim_data_plus/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_lints: ^1.0.0
permission_handler: ^6.0.0


flutter:

  plugin:
    platforms:
      android:
        package: com.example.sim_data_plus
        pluginClass: SimDataPlugin
      ios:
        pluginClass: SimInfoPlugin